startGame({
	fps: 60,
	background: '#5fcde4',
	spritesRoot: 'sprites',
	tilesRoot: 'tiles',
	scriptsRoot: 'scripts',
	objectsRoot: 'objects',
	soundsRoot: 'sounds',
	roomsRoot: 'rooms',
	sprites: [
		['player', 'idle.png'],
		['empty', 'empty.png'],
		['pig', 'pig.png'],
		['ball', 'ball.png'],
		['ballOpen', [...fromTo(0, 1)].map(i => `ballOpen/${i}.png`)],
		['toPigParticle', 'toPigParticle.png'],
		['ballParticle', 'ballParticle.png'],
		['onoffOn', 'onoffOn.png'],
		['onoffOn1', 'onoffOn1.png'],
		['onoffOff', 'onoffOff.png'],
		['toggleOn', 'toggle1.png'],
		['toggleOff', 'toggle2.png'],
		['portal', [...fromTo(0, 2)].map(i => `portal/${i}.png`)],
		['run', [...fromTo(0, 4)].map(i => `run/${i}.png`)],
		['pigWing', 'pigWing.png'],
		['pigWingOver', 'pigWingOver.png'],
		['pigOver', 'pigOver.png'],
		['cloud', 'cloud.png'],
		['pigBig', 'pigBig.png'],
		['one', 'one.png'],
        ['old', 'old.png'],
		['portalYes', 'portalYes.png'],
		['portalNo', 'portalNo.png'],
		['jump', 'jump.png'],
		['pigWing2', 'pigWing2.png'],
		['pigWingOver2', 'pigWingOver2.png'],
		['pigTp', 'pigTp.png'],
		['pigTpOver', 'pigTpOver.png'],
		['blackedLong', 'blackedLong.png'],
		['blackedCorner', 'blackedCorner.png'],
		['mountain', 'mountains.png'],
	],
	tiles: [
		['mapTiles', 'mapTiles.png'],
	],
	scripts: [
		'methods.js',
		'globals.js',
		'scripts.js',
		'ui/dialog.js',
		'ui/pigopedia.js',
		'ui/lvlname.js',
		'ui/mainmenu.js',
		'ui/buttons.js',
		'ui/ballui.js',
        'ui/menu.js',
		'ui/battlePic.js',
		'ui/joystick.js',
		'constants.js',
	],
	objects: [
		'player/player.js',
		'solid.js',
		'controls/control0.js',
		'controls/control.js',
		'controls/control2.js',
		'controls/control3.js',
		'controls/control4.js',
		'controls/control5.js',
		'controls/control6.js',
		'controls/control7.js',
		'controls/control8.js',
		'controls/control9.js',
		'controls/control10.js',
		'controls/control11.js',
		'controls/controlEnd.js',
		'camera/camera.js',
		'pigs/pig.js',
		'pigs/pigWing.js',
		'pigs/pigBig.js',
		'pigs/pigTp.js',
		'ball/ball.js',
		'ball/toPigParticle.js',
		'ball/tpParticle.js',
		'general/tail.js',
		'ball/ballParticle.js',
		'onoff.js',
		'onoff1.js',
		'toggle.js',
		'portal.js',
		'cloud.js',
		'controls/init.js',
		'one.js',
        'old.js',
		'mountain.js',
	],
	sounds: [
		['knock', 'knock.mp3'],
		['hru', 'hru.mp3'],
		['jump', 'jump.mp3'],
		['restart', 'restart.mp3'],
		['main', 'main.mp3'],
		['win', 'win.mp3'],
		['tp', 'tp.mp3'],
	],
	rooms: [
		{
			name: 'init',
			path: 'init.js',
			tileLayers: [],
		},
		{
			name: 'map0',
			path: 'map0.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map1',
			path: 'map1.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map2',
			path: 'map2.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map3',
			path: 'map3.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map4',
			path: 'map4.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map5',
			path: 'map5.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map6',
			path: 'map6.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map7',
			path: 'map7.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map8',
			path: 'map8.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map9',
			path: 'map9.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map10',
			path: 'map10.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map11',
			path: 'map11.js',
			tileLayers: [
				['mapTiles', 3],
				['mapTiles', 2],
				['mapTiles', 1],
			],
		},
		{
			name: 'map12',
			path: 'map12.js',
			tileLayers: [
				['mapTiles', 1],
			],
		},
	],
	entryPoint: 'init',
	debug: {
		fps: false,
		colliders: false,
	}
});