(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("map8",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"map8.js"
        }
    },
 "height":14,
 "infinite":false,
 "layers":[
        {
         "data":[13, 14, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 23, 24, 16, 17, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 26, 27, 19, 20, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 29, 30, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 13, 14, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 17, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 20, 21, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":14,
         "id":7,
         "name":"\u0421\u043b\u043e\u0439 \u0442\u0430\u0439\u043b\u043e\u0432 3",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "data":[7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
         "height":14,
         "id":6,
         "name":"\u0421\u043b\u043e\u0439 \u0442\u0430\u0439\u043b\u043e\u0432 2",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
         "height":14,
         "id":4,
         "name":"\u0421\u043b\u043e\u0439 \u0442\u0430\u0439\u043b\u043e\u0432 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"\u0421\u043b\u043e\u0439 \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432 1",
         "objects":[
                {
                 "height":0,
                 "id":7,
                 "name":"player",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":269.454545454545,
                 "y":400.810606060606
                }, 
                {
                 "height":0,
                 "id":13,
                 "name":"control8",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":16,
                 "y":16
                }, 
                {
                 "height":448,
                 "id":23,
                 "name":"solid",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":448,
                 "id":24,
                 "name":"solid",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":0
                }, 
                {
                 "height":32,
                 "id":26,
                 "name":"solid",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":576,
                 "x":32,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":98,
                 "name":"portal",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":559.833333333333,
                 "y":391.666666666667
                }, 
                {
                 "height":32,
                 "id":125,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":32,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":126,
                 "name":"toggle",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":32.25,
                 "y":99
                }, 
                {
                 "height":32,
                 "id":127,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":288,
                 "y":352
                }, 
                {
                 "height":32,
                 "id":128,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":320,
                 "y":352
                }, 
                {
                 "height":32,
                 "id":129,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":352,
                 "y":352
                }, 
                {
                 "height":0,
                 "id":133,
                 "name":"pig",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":561.333333333333,
                 "y":78.7189542483661
                }, 
                {
                 "height":32,
                 "id":134,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":64,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":135,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":128,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":136,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":416
                }, 
                {
                 "height":0,
                 "id":138,
                 "name":"pigTp",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":334.333333333333,
                 "y":334.666666666667
                }, 
                {
                 "height":32,
                 "id":139,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":160,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":140,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":141,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":142,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":143,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":288,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":144,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":320,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":145,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":384,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":146,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":352,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":147,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":148,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":149,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":150,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":480,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":151,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":152,
                 "name":"one",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":416
                }, 
                {
                 "height":32,
                 "id":160,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":161,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":160
                }, 
                {
                 "height":32,
                 "id":162,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":163,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":164,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":160
                }, 
                {
                 "height":32,
                 "id":165,
                 "name":"onoff",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":160
                }, 
                {
                 "height":32,
                 "id":166,
                 "name":"solid",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":96,
                 "x":32,
                 "y":128
                }, 
                {
                 "height":32,
                 "id":168,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":169,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":64
                }, 
                {
                 "height":32,
                 "id":170,
                 "name":"onoff1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":32
                }, 
                {
                 "height":160,
                 "id":171,
                 "name":"solid",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":480,
                 "y":32
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":9,
 "nextobjectid":172,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.3.1",
 "tileheight":32,
 "tilesets":[
        {
         "columns":3,
         "firstgid":1,
         "image":"..\/tiles\/mapTiles.png",
         "imageheight":352,
         "imagewidth":96,
         "margin":0,
         "name":"mapTiles",
         "spacing":0,
         "tilecount":33,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":20
});